# Generated by Django 3.1.2 on 2020-10-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='date_opened',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='hotel_pics'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='year_opened',
            field=models.PositiveSmallIntegerField(default=2016),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='desc',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.SET_DEFAULT, to='cities_light.subregion'),
        ),
    ]
