# Generated by Django 3.1.2 on 2020-10-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20201030_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='year_opened',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
    ]
