# Generated by Django 3.1.2 on 2020-10-30 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20201030_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='year_opened',
            field=models.PositiveSmallIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(2016)]),
        ),
    ]
